# -*- coding: utf-8 -*-
"""Cluster US/UK version 2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hgSqkpTmVov7aLfJL2qTfbXNbCAZqoWa
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pylab
from math import pi

from google.colab import files
uploaded = files.upload()

data_path = "ClusterUSUKversion.csv"
comparison = pd.read_csv(data_path, index_col=0)

print(comparison)

import matplotlib.pyplot as plt 

  
x =comparison['arrest/ pop size ']  
  
y =comparison[' prison pop / # of arrests'] 
plt.xlabel('Percentage of people arrested')
plt.ylabel('Percentage of people incarcerated')
plt.title('Comparison between the arrest and incarceration rate of the UK and Us states')

x_white, y_white =  [x[2*i] for i in range(5)],[y[2*i] for i in range(5)]
x_black, y_black =  [x[2*i+1] for i in range(5)],[y[2*i+1] for i in range(5)]
plt.scatter(x_white, y_white, c ="blue",label="white")
plt.scatter(x_black, y_black, c ="red",label="black")
plt.legend() 

states = [name[2:] for name in (list(comparison.index))] #List of the states, each state appears twice
for i in range(len(x)):
  #For each points, we print the name of the state at the position (x-1, y+1), so that it is centered above the corresponding dots
  plt.text(x[i]-1,y[i]+1,states[i],fontsize =8)
# To show the plot 
plt.show()

from google.colab import files
uploaded = files.upload()

data_path = "Percentageofthepoparrested2.csv"
poparrested = pd.read_csv(data_path, index_col=0)

print(poparrested)

import matplotlib.pyplot as plt 
import numpy as np
  
x =poparrested['Percentage of the population arrested (white people)']  
  
y =poparrested['Percentage of the population arrested (black people)'] 
plt.xlabel('Percentage of the population arrested among white people ')
plt.ylabel('Percentage of the population arrested among black people')

plt.title('Percentage of the population arrested among two populations in UK and US states')
plt.plot(np.linspace(0,20),np.linspace(0,20),linestyle='-.')
plt.scatter(x, y, c='blue') 

states = [name for name in (list(poparrested.index))] #List of the states, each state appears twice
for i in range(len(x)):
  #For each points, we print the name of the state at the position (x-1, y+1), so that it is centered above the corresponding dots
  plt.text(x[i]-1,y[i]+1,states[i],fontsize =8)

from scipy import stats
import numpy as np
a, b, r_value, p_value, std_err = stats.linregress(x,y)
t = np.linspace(0,15)
plt.plot(t,a*t+b)
plt.xlim([0,15])
plt.ylim([0,15])
# To show the plot 
plt.show()
print(a)

from google.colab import files
uploaded = files.upload()

data_path = "Percentageofpoincarceratedamongpeoplearrested4.csv"
popincarcerated = pd.read_csv(data_path, index_col=0)

print(popincarcerated)

import matplotlib.pyplot as plt 
import numpy as np
  
x =popincarcerated['Percentage of the population incarcerated among white people arrested']  
  
y =popincarcerated['Percentage of the population incarcerated among black people arrested'] 
plt.xlabel('Percentage of the population incarcerated among white people arrested')
plt.ylabel('Percentage of the population incarcerated among black people arrested')

plt.title('Percentage of the population incarcerated among two populations arrested in UK and US states')
plt.plot(np.linspace(0,40),np.linspace(0,40),linestyle='-.')
plt.scatter(x, y, c='blue') 

states = [name for name in (list(popincarcerated.index))] #List of the states, each state appears twice
for i in range(len(x)):
  #For each points, we print the name of the state at the position (x-1, y+1), so that it is centered above the corresponding dots
  plt.text(x[i]-1,y[i]+1,states[i],fontsize =8)

from scipy import stats
import numpy as np
a, b, r_value, p_value, std_err = stats.linregress(x,y)
t = np.linspace(0,35)
plt.plot(t,a*t+b)

# To show the plot 
plt.show()
print(a)