# -*- coding: utf-8 -*-
"""SOUTH DAKOTA Arrest Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10iVfY_TbBf7JUU4Mba4E3dlHlHjy5Sr_
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pylab
from math import pi

from google.colab import files
uploaded = files.upload()

data_path = 'SDArrests.csv'
arrests = pd.read_csv(data_path, index_col=0)
arrests.head()

#arrests.isnull().sum()
newArrests = arrests.fillna(" ")
newArrests.isnull().sum()

data_path2 = "Race and Ethnicity.csv"
data = pd.read_csv(data_path2, index_col=5)
data.head()
population = data.loc[2018, ['Race', 'Population', 'share']]
population

transposedArrests = np.transpose(newArrests)
clean = transposedArrests['Total'].loc['Asian':'Unknown']
clean

r = ['White', 'Black', 'Indian', 'Asian', 'Islander', 'Other']
rawData = {'greenBars':[10357, 1621, 6229, 163, 36, 2269], 'blueBars':[718783+22087, 18895+162, 74907+3161, 14791+232, 51, 271+5511+20554+2830]}
df = pd.DataFrame(rawData)

totals = [i+j for i,j in zip(df['greenBars'], df['blueBars'])]
greenBars = [i / j * 100 for i,j in zip(df['greenBars'], totals)]
blueBars = [i / j * 100 for i,j in zip(df['blueBars'], totals)]

fig, ax=plt.subplots(figsize = (5,10))
barWidth = 0.85
names = r
plt.bar(r, greenBars, color='#b5ffb9', edgecolor='white', width=barWidth)
plt.bar(r, blueBars, bottom=greenBars, color='#a3acff', edgecolor='white', width=barWidth)

plt.title('Arrests as % of Total Population for each Race in South Dakota')
plt.xticks(r, names)
plt.xlabel("Race")
plt.ylabel("%")
plt.show()

r = ['White', 'Black', 'Other']
rawData = {'greenBars':[10357, 1621, 6229+163+36+2269], 'blueBars':[718783+22087, 18895+162, 74907+3161+14791+232+51+271+5511+20554+2830]}
df = pd.DataFrame(rawData)

totals = [i+j for i,j in zip(df['greenBars'], df['blueBars'])]
greenBars = [i / j * 100 for i,j in zip(df['greenBars'], totals)]
blueBars = [i / j * 100 for i,j in zip(df['blueBars'], totals)]

fig, ax=plt.subplots(figsize = (5,10))
barWidth = 0.85
names = r
plt.bar(r, greenBars, color='#7F8DA8', edgecolor='white', width=barWidth)
plt.bar(r, blueBars, bottom=greenBars, color='#FADFC3', edgecolor='white', width=barWidth)

plt.ylim(0,30)
plt.title('Arrests as % of Population in South Dakota', fontsize=14)
plt.xticks(r, names)
plt.xlabel("Race", fontsize=14)
plt.ylabel("Percentage", fontsize=14)
plt.show()

data_path = 'southdakota.csv'
prison = pd.read_csv(data_path, index_col=0)
prison.loc['Prison Population']

race = ['White', 'Black', 'Hispanic', 'Other']
prisonPop = [2121, 308, 154, 1273]

fig, ax=plt.subplots(figsize = (5,5)) ##creating bar chart
plt.bar(race, prisonPop)
plt.xlabel('Race')
plt.ylabel('Prison Population')
plt.title('Prison Population in South Dakota in 2019 by Race')
for i, data in enumerate(prisonPop): ##adding labels to bars
  plt.text(x=i, y=data+1, s=f"{data}", ha='center') 
plt.show()

r = ['White', 'Black', 'Other']
rawData = {'blueBars':[10357, 1621, 6229+163+36+2269], 'greenBars':[2121, 308, 154+1273]}
df = pd.DataFrame(rawData)

totals = [i+j for i,j in zip(df['greenBars'], df['blueBars'])]
greenBars = [i / j * 100 for i,j in zip(df['greenBars'], totals)]
blueBars = [i / j * 100 for i,j in zip(df['blueBars'], totals)]

fig, ax=plt.subplots(figsize = (5,10))
barWidth = 0.85
names = r
plt.bar(r, greenBars, color='#7F8DA8', edgecolor='white', width=barWidth)
plt.bar(r, blueBars, bottom=greenBars, color='#FADFC3', edgecolor='white', width=barWidth)

plt.ylim(0,30)
plt.title('Prison Population as % of Arrests in South Dakota', fontsize=14)
plt.xticks(r, names)
plt.xlabel("Race", fontsize=14)
plt.ylabel("Percentage", fontsize=14)
plt.show()